-- Optional Mortéa sample approved professionals
-- Run this in Supabase SQL Editor if you want test profiles to appear on the live map/discover pages.

insert into professionals (
  business_name,
  owner_name,
  email,
  phone,
  category,
  country,
  province,
  city,
  address,
  description,
  services_offered,
  instagram,
  whatsapp,
  website,
  booking_link,
  membership,
  status,
  latitude,
  longitude
) values
(
  'Maison Élise Head Spa',
  'Élise Founder',
  'maisonelise@example.com',
  '+1 514 000 0000',
  'Head Spa',
  'Canada',
  'Québec',
  'Montréal',
  'Montréal, QC',
  'Premium head spa rituals with calming scalp therapy and luxury relaxation.',
  'Signature Head Spa Ritual, Scalp Wellness Treatment, Relaxation Add-on',
  'https://instagram.com/',
  'https://wa.me/15140000000',
  'https://example.com',
  'https://example.com/book',
  'Founder Access',
  'approved',
  45.5017,
  -73.5673
),
(
  'Studio Velour',
  'Velour Founder',
  'studio@example.com',
  '+1 416 000 0000',
  'Mobile Beauty',
  'Canada',
  'Ontario',
  'Toronto',
  'Toronto, ON',
  'Mobile beauty concierge for events, bridal mornings, and private appointments.',
  'Bridal Beauty, Mobile Makeup, Private Concierge',
  'https://instagram.com/',
  'https://wa.me/14160000000',
  'https://example.com',
  'https://example.com/book',
  'Founder Access',
  'approved',
  43.6532,
  -79.3832
),
(
  'Éther Wellness',
  'Éther Founder',
  'ether@example.com',
  '+971 50 000 0000',
  'Private Wellness',
  'UAE',
  'Dubai',
  'Dubai',
  'Dubai, UAE',
  'Luxury massage and private wellness experiences for modern clients.',
  'Private Wellness Session, Luxury Massage, Recovery Ritual',
  'https://instagram.com/',
  'https://wa.me/971500000000',
  'https://example.com',
  'https://example.com/book',
  'Founder Access',
  'approved',
  25.2048,
  55.2708
);

-- To approve a new professional application later:
-- update professionals set status = 'approved' where email = 'their-email@example.com';
